squid:
  image: jrevolt/squid
  volumes:
  - squid-etc:/etc/squid
  - squid-data:/var/cache/squid
  - squid-log:/var/log/squid
  ports:
  - 3128:3128/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
